name: ci

on:
   workflow_dispatch:
   schedule:
     - cron: 0 0 1 * 0     # monthly
   pull_request:
     branches:
       - main
   push:
     branches:
       - main

jobs:
  tox:
    strategy:
      matrix:
        os: [ubuntu-latest] #[ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10','3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 # Use v4 for compatibility with pyproject.toml
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]

      - name: Clone and install pynapple
        run: |
          cd ../
          git clone -b dev https://github.com/pynapple-org/pynapple.git
          cd pynapple/
          pip install -e .
          cd ../pynajax/

      - name: Run nox
        run: |
          nox

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  check:
    if: always()
    needs: tox
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether all tests and notebooks succeeded
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
